### ISSUE TITLE
Cannot collect proceeds after winner revealed

### ISSUE THREAD

**Issue by amolbiswas** [draffle-io/draffle#16]
All the cli commands are working as expected except "collect-proceeds". When I execute this command, it fails after very long time (several minutes) and says 
"Error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds".

But the creator wallet has enough SOLs.

Here is raffle address: 8ttBaj5BC4Wx7nsw9BaNCiLYXuKjRGVD5AnBsxbHBbX9

![image](https://user-images.githubusercontent.com/92605385/169503496-e87c8160-b7b0-4896-9fd8-cc69f31f5d8d.png)

**Comment by Fahad-pnw** [comment]
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/9507146/176529825-aaa5e3d6-c7d8-44f6-a9bc-7bee5f4f36bc.png">
i have a similar but not exact issue...

**Comment by gabrielhicks** [comment]
Hello! Wanted to check in to see your issue is resolved. Noticed this transaction: 

https://solscan.io/tx/5ZEZyn5BiSiRu2qAbENQZigLCgjdoA2S4Cr7DGHraCPuv1kWJAMzDGWqNt6e8ATA1CoqksP559Gff9YFoJbFy4iv

Which shows 50 NEST token being withdrawn from 8ttBaj5BC4Wx7nsw9BaNCiLYXuKjRGVD5AnBsxbHBbX9 to AQ2hdJpeR8mKGwCRf9WdQ2owNdMHuCUm12JmNdwX1imv

**Comment by moneytoad888** [comment]
Seems to be resolved as observed
